import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey, Index, Integer, Numeric, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from backend.app.models.base import Base

class BusinessInsight(Base):
    """
    Deterministic insights generated by the InsightEngine from Analytics and Intel rollups.
    """
    __tablename__ = "business_insights"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    workspace_id = Column(UUID(as_uuid=True), ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False)
    
    title = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    category = Column(String, nullable=False)
    
    confidence = Column(Numeric(5, 2), nullable=False)
    confidence_reason = Column(Text, nullable=True)
    priority = Column(String, nullable=False)  # low, medium, high, critical
    
    status = Column(String, nullable=False, default="active")  # active, archived, superseded
    
    evidence_snapshot = Column(JSONB, nullable=False) # e.g. metric name, value, date range, comparison
    
    insight_version = Column(Integer, nullable=False, default=1)
    generated_by_engine_version = Column(String, nullable=False)
    engine_config_version = Column(String, nullable=False)
    
    data_freshness_timestamp = Column(DateTime(timezone=True), nullable=False)
    snapshot_id = Column(UUID(as_uuid=True), nullable=False)
    
    fingerprint = Column(String, nullable=False)  # deduplication hash
    
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False)

    __table_args__ = (
        Index("ix_business_insight_workspace", "workspace_id"),
        Index("ix_business_insight_fingerprint", "workspace_id", "fingerprint", unique=True),
        Index("ix_business_insight_status", "status"),
    )

class InsightLineage(Base):
    """Explicit references back to the rollups used to generate the insight."""
    __tablename__ = "insight_lineage"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    insight_id = Column(UUID(as_uuid=True), ForeignKey("business_insights.id", ondelete="CASCADE"), nullable=False)
    
    source_type = Column(String, nullable=False) # e.g. AnalyticsDailyRollup, IntelDailyTopicRollup
    source_identifier = Column(String, nullable=False) # e.g. metric_name or topic_name
    source_version = Column(String, nullable=True)
    source_date_range = Column(JSONB, nullable=False) # {"start": ..., "end": ...}
    
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False)

    __table_args__ = (
        Index("ix_insight_lineage_insight_id", "insight_id"),
    )


class BusinessRecommendation(Base):
    """
    Actionable recommendations mapped from a BusinessInsight.
    """
    __tablename__ = "business_recommendations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    workspace_id = Column(UUID(as_uuid=True), ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False)
    insight_id = Column(UUID(as_uuid=True), ForeignKey("business_insights.id", ondelete="CASCADE"), nullable=False)
    
    recommendation = Column(Text, nullable=False)
    rationale = Column(Text, nullable=False)
    
    confidence = Column(Numeric(5, 2), nullable=False)
    priority = Column(String, nullable=False)  # low, medium, high, critical
    
    recommendation_engine_version = Column(String, nullable=False)
    recommendation_rule_id = Column(String, nullable=False)
    
    effectiveness_status = Column(String, nullable=False, default="unknown") # unknown, effective, ineffective
    reviewed_at = Column(DateTime(timezone=True), nullable=True)
    review_notes = Column(Text, nullable=True)
    
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False)

    __table_args__ = (
        Index("ix_business_rec_workspace", "workspace_id"),
        Index("ix_business_rec_insight", "insight_id"),
    )


class ExecutiveReport(Base):
    """
    Generated structured reports aggregating insights and recommendations.
    """
    __tablename__ = "executive_reports"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    workspace_id = Column(UUID(as_uuid=True), ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False)
    
    report_type = Column(String, nullable=False)  # daily, weekly, monthly
    report_period = Column(String, nullable=False)  # e.g., "2023-W41"
    
    summary = Column(JSONB, nullable=False)  # Structured JSON for the report sections (overview, key_findings, conflicts, etc.)
    
    report_version = Column(Integer, nullable=False, default=1)
    generated_by_engine_version = Column(String, nullable=False)
    engine_config_version = Column(String, nullable=False)
    
    data_freshness_timestamp = Column(DateTime(timezone=True), nullable=False)
    snapshot_id = Column(UUID(as_uuid=True), nullable=False)
    
    fingerprint = Column(String, nullable=False) # deduplication hash
    
    generated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False)

    __table_args__ = (
        Index("ix_executive_report_workspace", "workspace_id"),
        Index("ix_executive_report_fingerprint", "workspace_id", "fingerprint", unique=True),
    )


class BusinessQuestionAudit(Base):
    """
    Tracks all internal Business Analyst requests (questions).
    """
    __tablename__ = "business_question_audit"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    workspace_id = Column(UUID(as_uuid=True), ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False)
    
    question = Column(Text, nullable=False)
    classification = Column(String, nullable=False) # factual, trend, unsupported_prediction
    
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False)

    __table_args__ = (
        Index("ix_question_audit_workspace", "workspace_id"),
        Index("ix_question_audit_created_at", "created_at"),
    )
