"""Add Workflow Builder models

Revision ID: 32f007f85e86
Revises: 88e3fe034baa
Create Date: 2026-06-24 21:31:46.487966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32f007f85e86'
down_revision: Union[str, Sequence[str], None] = '88e3fe034baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agents_workspace', 'agents', ['workspace_id'], unique=False)
    op.create_table('workflow_dead_letter_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_reason', sa.String(length=1000), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_dead_letter_events_workspace', 'workflow_dead_letter_events', ['workspace_id'], unique=False)
    op.create_table('workflow_event_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_event_queue_status', 'workflow_event_queue', ['status'], unique=False)
    op.create_index('idx_workflow_event_queue_workspace', 'workflow_event_queue', ['workspace_id'], unique=False)
    op.create_table('workflow_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_logs_workflow', 'workflow_logs', ['workflow_id'], unique=False)
    op.create_index('idx_workflow_logs_workspace', 'workflow_logs', ['workspace_id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_versions_workflow', 'workflow_versions', ['workflow_id'], unique=False)
    op.create_table('workflow_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('source_handle', sa.String(length=100), nullable=True),
    sa.Column('target_handle', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['workflow_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_edges_version', 'workflow_edges', ['version_id'], unique=False)
    op.create_table('workflow_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ui_position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['workflow_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_nodes_version', 'workflow_nodes', ['version_id'], unique=False)
    op.create_table('workflow_run_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_run_steps_node', 'workflow_run_steps', ['node_id'], unique=False)
    op.create_index('idx_workflow_run_steps_run', 'workflow_run_steps', ['run_id'], unique=False)
    op.add_column('workflow_runs', sa.Column('version_id', sa.UUID(), nullable=True))
    op.create_index('idx_workflow_runs_version', 'workflow_runs', ['version_id'], unique=False)
    op.create_foreign_key('fk_workflow_runs_version_id', 'workflow_runs', 'workflow_versions', ['version_id'], ['id'], ondelete='CASCADE')
    op.add_column('workflows', sa.Column('active_version_id', sa.UUID(), nullable=True))
    op.add_column('workflows', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key('fk_workflows_active_version_id', 'workflows', 'workflow_versions', ['active_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workflows_active_version_id_fkey', 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'updated_at')
    op.drop_column('workflows', 'active_version_id')
    op.drop_constraint('workflow_runs_version_id_fkey', 'workflow_runs', type_='foreignkey')
    op.drop_index('idx_workflow_runs_version', table_name='workflow_runs')
    op.drop_column('workflow_runs', 'version_id')
    # Removed backup table recreation and index
    op.drop_index('idx_workflow_run_steps_run', table_name='workflow_run_steps')
    op.drop_index('idx_workflow_run_steps_node', table_name='workflow_run_steps')
    op.drop_table('workflow_run_steps')
    op.drop_index('idx_workflow_nodes_version', table_name='workflow_nodes')
    op.drop_table('workflow_nodes')
    op.drop_index('idx_workflow_edges_version', table_name='workflow_edges')
    op.drop_table('workflow_edges')
    op.drop_index('idx_workflow_versions_workflow', table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index('idx_workflow_logs_workspace', table_name='workflow_logs')
    op.drop_index('idx_workflow_logs_workflow', table_name='workflow_logs')
    op.drop_table('workflow_logs')
    op.drop_index('idx_workflow_event_queue_workspace', table_name='workflow_event_queue')
    op.drop_index('idx_workflow_event_queue_status', table_name='workflow_event_queue')
    op.drop_table('workflow_event_queue')
    op.drop_index('idx_workflow_dead_letter_events_workspace', table_name='workflow_dead_letter_events')
    op.drop_table('workflow_dead_letter_events')
    op.drop_index('idx_agents_workspace', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
