"""add_agent_platform_database_layer

Revision ID: 65b8b00d3560
Revises: 32f007f85e86
Create Date: 2026-06-25 18:56:10.312378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65b8b00d3560'
down_revision: Union[str, Sequence[str], None] = '32f007f85e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_platform_owned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channels_workspace', 'channels', ['workspace_id'], unique=False)
    op.create_table('workspace_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workspace_memory_workspace', 'workspace_memory', ['workspace_id'], unique=False)
    op.create_table('agent_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'agent_id', name='uq_agent_channels_mapping')
    )
    op.create_index('idx_agent_channels_workspace', 'agent_channels', ['workspace_id'], unique=False)
    op.create_table('agent_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_memory_agent', 'agent_memory', ['agent_id'], unique=False)
    op.create_index('idx_agent_memory_workspace', 'agent_memory', ['workspace_id'], unique=False)
    op.create_table('agent_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('total_conversations', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_metrics_agent', 'agent_metrics', ['agent_id'], unique=False)
    op.create_index('idx_agent_metrics_workspace', 'agent_metrics', ['workspace_id'], unique=False)
    op.create_table('agent_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'user_id', name='uq_agent_permissions_agent_user')
    )
    op.create_index('idx_agent_permissions_workspace', 'agent_permissions', ['workspace_id'], unique=False)
    op.create_table('agent_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version_number', name='uq_agent_id_version_number')
    )
    op.create_index('idx_agent_versions_agent', 'agent_versions', ['agent_id'], unique=False)
    op.create_index('idx_one_published_version', 'agent_versions', ['agent_id'], unique=True, postgresql_where=sa.text('is_published = true'))
    op.create_table('agent_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['agent_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_table('agent_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('welcome_prompt', sa.Text(), nullable=True),
    sa.Column('fallback_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['agent_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['agent_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_runs_conversation', 'agent_runs', ['conversation_id'], unique=False)
    op.create_index('idx_agent_runs_workspace', 'agent_runs', ['workspace_id'], unique=False)
    op.create_table('agent_tool_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('tool_type', sa.String(length=50), nullable=False),
    sa.Column('tool_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['agent_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_memory_conversation', 'conversation_memory', ['conversation_id'], unique=False)
    op.create_index('idx_conversation_memory_workspace', 'conversation_memory', ['workspace_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('participant_type', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'participant_id')
    )
    op.create_index('idx_conversation_participants_workspace', 'conversation_participants', ['workspace_id'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_logs_agent', 'agent_logs', ['agent_id'], unique=False)
    op.create_index('idx_agent_logs_run', 'agent_logs', ['run_id'], unique=False)
    op.create_index('idx_agent_logs_workspace', 'agent_logs', ['workspace_id'], unique=False)
    op.create_table('agent_run_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_run_steps_run', 'agent_run_steps', ['run_id'], unique=False)
    op.create_index('idx_agent_run_steps_workspace', 'agent_run_steps', ['workspace_id'], unique=False)
    op.create_table('agent_decision_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('run_step_id', sa.UUID(), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('memory_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('knowledge_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workflow_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_tokens', sa.Integer(), nullable=True),
    sa.Column('execution_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['agent_prompts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_step_id'], ['agent_run_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_step_id')
    )
    op.create_index('idx_agent_decision_traces_workspace', 'agent_decision_traces', ['workspace_id'], unique=False)
    op.add_column('agents', sa.Column('template_id', sa.UUID(), nullable=True))
    op.add_column('agents', sa.Column('category', sa.String(length=255), nullable=False))
    op.add_column('agents', sa.Column('avatar_url', sa.String(length=1000), nullable=True))
    op.add_column('agents', sa.Column('is_public_allowed', sa.Boolean(), nullable=False))
    op.add_column('agents', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('agents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key(None, 'agents', 'agent_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.drop_column('agents', 'status')
    op.drop_column('agents', 'description')
    op.drop_column('agents', 'capabilities')
    op.add_column('conversations', sa.Column('channel_id', sa.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('active_participant_id', sa.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('last_responding_participant_id', sa.UUID(), nullable=True))
    op.add_column('conversations', sa.Column('handoff_status', sa.String(length=50), nullable=False))
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('conversations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('idx_conversations_channel'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_customer'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_external'), table_name='conversations')
    op.drop_constraint(op.f('uq_workspace_conversation_external_id'), 'conversations', type_='unique')
    op.create_index('idx_conversations_channel_id', 'conversations', ['channel_id'], unique=False)
    op.drop_constraint(op.f('conversations_customer_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'channels', ['channel_id'], ['id'], ondelete='SET NULL')
    op.drop_column('conversations', 'last_handoff_reason')
    op.drop_column('conversations', 'previous_agent')
    op.drop_column('conversations', 'loop_cooldown_until')
    op.drop_column('conversations', 'customer_id')
    op.drop_column('conversations', 'current_state')
    op.drop_column('conversations', 'external_id')
    op.drop_column('conversations', 'unresolved_intent')
    op.drop_column('conversations', 'current_state_version')
    op.drop_column('conversations', 'ended_at')
    op.drop_column('conversations', 'handoff_count')
    op.drop_column('conversations', 'current_agent')
    op.drop_column('conversations', 'started_at')
    op.drop_column('conversations', 'last_handoff_at')
    op.drop_column('conversations', 'channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('channel', sa.VARCHAR(length=50), server_default=sa.text("'web'::character varying"), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('last_handoff_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('current_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('handoff_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('current_state_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('unresolved_intent', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('current_state', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('loop_cooldown_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('previous_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('last_handoff_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('conversations_channel_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_customer_id_fkey'), 'conversations', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_conversations_channel_id', table_name='conversations')
    op.create_unique_constraint(op.f('uq_workspace_conversation_external_id'), 'conversations', ['workspace_id', 'external_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_conversations_external'), 'conversations', ['external_id'], unique=False)
    op.create_index(op.f('idx_conversations_customer'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('idx_conversations_channel'), 'conversations', ['channel'], unique=False)
    op.alter_column('conversations', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'handoff_status')
    op.drop_column('conversations', 'last_responding_participant_id')
    op.drop_column('conversations', 'active_participant_id')
    op.drop_column('conversations', 'channel_id')
    op.add_column('agents', sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('agents', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('agents_template_id_fkey'), 'agents', type_='foreignkey')
    op.drop_column('agents', 'updated_at')
    op.drop_column('agents', 'is_active')
    op.drop_column('agents', 'is_public_allowed')
    op.drop_column('agents', 'avatar_url')
    op.drop_column('agents', 'category')
    op.drop_column('agents', 'template_id')
    op.drop_index('idx_agent_decision_traces_workspace', table_name='agent_decision_traces')
    op.drop_table('agent_decision_traces')
    op.drop_index('idx_agent_run_steps_workspace', table_name='agent_run_steps')
    op.drop_index('idx_agent_run_steps_run', table_name='agent_run_steps')
    op.drop_table('agent_run_steps')
    op.drop_index('idx_agent_logs_workspace', table_name='agent_logs')
    op.drop_index('idx_agent_logs_run', table_name='agent_logs')
    op.drop_index('idx_agent_logs_agent', table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index('idx_conversation_participants_workspace', table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index('idx_conversation_memory_workspace', table_name='conversation_memory')
    op.drop_index('idx_conversation_memory_conversation', table_name='conversation_memory')
    op.drop_table('conversation_memory')
    op.drop_table('agent_tool_policies')
    op.drop_index('idx_agent_runs_workspace', table_name='agent_runs')
    op.drop_index('idx_agent_runs_conversation', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('agent_prompts')
    op.drop_table('agent_models')
    op.drop_index('idx_one_published_version', table_name='agent_versions', postgresql_where=sa.text('is_published = true'))
    op.drop_index('idx_agent_versions_agent', table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index('idx_agent_permissions_workspace', table_name='agent_permissions')
    op.drop_table('agent_permissions')
    op.drop_index('idx_agent_metrics_workspace', table_name='agent_metrics')
    op.drop_index('idx_agent_metrics_agent', table_name='agent_metrics')
    op.drop_table('agent_metrics')
    op.drop_index('idx_agent_memory_workspace', table_name='agent_memory')
    op.drop_index('idx_agent_memory_agent', table_name='agent_memory')
    op.drop_table('agent_memory')
    op.drop_index('idx_agent_channels_workspace', table_name='agent_channels')
    op.drop_table('agent_channels')
    op.drop_index('idx_workspace_memory_workspace', table_name='workspace_memory')
    op.drop_table('workspace_memory')
    op.drop_index('idx_channels_workspace', table_name='channels')
    op.drop_table('channels')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
