"""Add missing fields to public_api_keys

Revision ID: 7af19d3cd42e
Revises: h0m4p15q3f78
Create Date: 2026-06-24 17:57:47.070602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af19d3cd42e'
down_revision: Union[str, Sequence[str], None] = 'h0m4p15q3f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_api_key_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_api_key_id', sa.UUID(), nullable=True),
    sa.Column('new_api_key_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['api_key_id'], ['public_api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_public_api_key_audit_api_key_id', 'public_api_key_audit', ['api_key_id'], unique=False)
    op.create_index('ix_public_api_key_audit_workspace_id', 'public_api_key_audit', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_analytics_daily_rollups_id'), 'analytics_daily_rollups', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_daily_rollups_metric_name'), 'analytics_daily_rollups', ['metric_name'], unique=False)
    op.create_index(op.f('ix_analytics_daily_rollups_time_bucket'), 'analytics_daily_rollups', ['time_bucket'], unique=False)
    op.create_index(op.f('ix_analytics_daily_rollups_workspace_id'), 'analytics_daily_rollups', ['workspace_id'], unique=False)
    op.drop_constraint('analytics_events_idempotency_key_key', 'analytics_events', type_='unique')
    op.drop_index('ix_analytics_events_idempotency_key', table_name='analytics_events')
    op.create_index(op.f('ix_analytics_events_idempotency_key'), 'analytics_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_hourly_rollups_id'), 'analytics_hourly_rollups', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_hourly_rollups_metric_name'), 'analytics_hourly_rollups', ['metric_name'], unique=False)
    op.create_index(op.f('ix_analytics_hourly_rollups_time_bucket'), 'analytics_hourly_rollups', ['time_bucket'], unique=False)
    op.create_index(op.f('ix_analytics_hourly_rollups_workspace_id'), 'analytics_hourly_rollups', ['workspace_id'], unique=False)
    op.drop_index('ix_outbox_idempotency_key', table_name='analytics_outbox')
    op.create_index(op.f('ix_analytics_outbox_idempotency_key'), 'analytics_outbox', ['idempotency_key'], unique=False)
    op.create_index('ix_question_audit_created_at', 'business_question_audit', ['created_at'], unique=False)
    op.add_column('public_api_keys', sa.Column('status', sa.String(), nullable=False))
    op.add_column('public_api_keys', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('public_api_keys', sa.Column('revoked_by', sa.UUID(), nullable=True))
    op.add_column('public_api_keys', sa.Column('request_count', sa.Integer(), nullable=False))
    op.add_column('public_api_keys', sa.Column('last_ip', sa.String(), nullable=True))
    op.add_column('public_api_keys', sa.Column('last_user_agent', sa.String(), nullable=True))
    op.add_column('public_api_keys', sa.Column('rate_limit_tier', sa.String(), nullable=False))
    op.create_index('ix_public_api_keys_status', 'public_api_keys', ['status'], unique=False)
    op.create_foreign_key(None, 'public_api_keys', 'users', ['revoked_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('voice_interactions_conversation_id_fkey', 'voice_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'voice_interactions', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_interactions', type_='foreignkey')
    op.create_foreign_key('voice_interactions_conversation_id_fkey', 'voice_interactions', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'public_api_keys', type_='foreignkey')
    op.drop_index('ix_public_api_keys_status', table_name='public_api_keys')
    op.drop_column('public_api_keys', 'rate_limit_tier')
    op.drop_column('public_api_keys', 'last_user_agent')
    op.drop_column('public_api_keys', 'last_ip')
    op.drop_column('public_api_keys', 'request_count')
    op.drop_column('public_api_keys', 'revoked_by')
    op.drop_column('public_api_keys', 'revoked_at')
    op.drop_column('public_api_keys', 'status')
    op.drop_index('ix_question_audit_created_at', table_name='business_question_audit')
    op.drop_index(op.f('ix_analytics_outbox_idempotency_key'), table_name='analytics_outbox')
    op.create_index('ix_outbox_idempotency_key', 'analytics_outbox', ['idempotency_key'], unique=False)
    op.drop_index(op.f('ix_analytics_hourly_rollups_workspace_id'), table_name='analytics_hourly_rollups')
    op.drop_index(op.f('ix_analytics_hourly_rollups_time_bucket'), table_name='analytics_hourly_rollups')
    op.drop_index(op.f('ix_analytics_hourly_rollups_metric_name'), table_name='analytics_hourly_rollups')
    op.drop_index(op.f('ix_analytics_hourly_rollups_id'), table_name='analytics_hourly_rollups')
    op.drop_index(op.f('ix_analytics_events_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_idempotency_key'), table_name='analytics_events')
    op.create_index('ix_analytics_events_idempotency_key', 'analytics_events', ['idempotency_key'], unique=False)
    op.create_unique_constraint('analytics_events_idempotency_key_key', 'analytics_events', ['idempotency_key'])
    op.drop_index(op.f('ix_analytics_daily_rollups_workspace_id'), table_name='analytics_daily_rollups')
    op.drop_index(op.f('ix_analytics_daily_rollups_time_bucket'), table_name='analytics_daily_rollups')
    op.drop_index(op.f('ix_analytics_daily_rollups_metric_name'), table_name='analytics_daily_rollups')
    op.drop_index(op.f('ix_analytics_daily_rollups_id'), table_name='analytics_daily_rollups')
    op.drop_index('ix_public_api_key_audit_workspace_id', table_name='public_api_key_audit')
    op.drop_index('ix_public_api_key_audit_api_key_id', table_name='public_api_key_audit')
    op.drop_table('public_api_key_audit')
    # ### end Alembic commands ###
