"""Add embedding metadata to documents

Revision ID: a81246da229c
Revises: 7af19d3cd42e
Create Date: 2026-06-24 18:55:12.068415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81246da229c'
down_revision: Union[str, Sequence[str], None] = '7af19d3cd42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('embedding_dim', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('embedded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedded_at')
    op.drop_column('documents', 'embedding_dim')
    op.drop_column('documents', 'embedding_model')
    # ### end Alembic commands ###
